### ISSUE TITLE
web3.eth.accounts are not used

### ISSUE THREAD

**Issue by destenson** [etheropt/etheropt.github.io#3]
When accessing etheropt.github.io from within Mist, etheropt is unaware of the accounts made available by Mist.

**Comment by flyswatter** [comment]
This issue could be made even more generic to be "`web3.eth.accounts` are not used", as this page right now does identity management within the page. Now with Mist and MetaMask available, there are decent web3 browsing options on the table.

**Comment by destenson** [comment]
Change made. I was unaware of the exact mechanism that enabled account usage from within Mist. Thanks.

**Comment by destenson** [comment]
How much code do you think it will take to change this? I might give it a crack if it's a straightforward fix. I probably will anyway, just to get my hands dirty.

**Comment by flyswatter** [comment]
If you're lucky, the simplest change could be adding three lines, the check for an already-existing global web3 object.

This kind of web3 check is well documented in [the Metamask Compatibility guide](https://github.com/MetaMask/faq) (which results in Mist-compliant dapps as well).

The web3 check would go [right about at this line](https://github.com/etheropt/etheropt.github.io/blob/722802ace0c7868bb98cab8f31c0f97e1363806f/server.js#L33), with the `HttpProvider` line being part of the fallback.

The other most common incompatibility would be if EtherOpt happens to use synchronous web3 methods, which MetaMask doesn't support, but I think Mist does.  I don't recommend using them in either case, but purging them could be a second issue.

**Comment by flyswatter** [comment]
Oh the other thing that's good to do that isn't a popular best practice yet, is to always [check the current network](https://github.com/MetaMask/faq#network-check), and load in the main-net or test-net contracts in response.  This makes for a really smooth experience, where someone can visit with their main-net or test-net browser and not have to think twice about it, because they already told their browser which network to use.

**Comment by destenson** [comment]
This has apparently been fixed in the latest build. Sweet :+1:
